name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t react-app .
          docker tag react-app ${{ secrets.DOCKER_REGISTRY }}/react-app:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/react-app:latest

      - name: Configure kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml
