name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t react-app .
          docker tag react-app ${{ secrets.DOCKER_REGISTRY }}/mayyazmunir/react-app:latest
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/mayyazmunir/react-app:latest

      - name: Configure kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-south-1

      - name: Update kubeconfig
        run: aws eks --region us-west-2 update-kubeconfig --name your-cluster-name

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml
